knowledge_base_file: knowledgebase.json
question_embeddings_file: question_embeddings.npy
index_file: index.faiss
sentence_transformer_model: all-MiniLM-L6-v2
openai_model: gpt-4 #e.g. gpt-4 or gpt-3.5-turbo
token_limit: 8192 #4097 max limit for gpt-3.5, 8192 for gpt-4
openai_api_key: ENV_OPENAI_API_KEY


